# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/events/events/commands/create_order.proto3

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/events/events/commands/create_order.proto3", :syntax => :proto3) do
    add_message "events.commands.CreateOrder" do
      optional :code, :string, 1
    end
  end
end

module Events
  module Commands
    CreateOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("events.commands.CreateOrder").msgclass
  end
end

